name: build

on:
  push:
    branches: ["*"]
    pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            base-devel
            git
            p7zip
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-freetype
          update: true
      - name: Build ImPlay
        shell: msys2 {0}
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE ..
          cmake --build . --target package
      - uses: actions/upload-artifact@v3
        with:
          name: ImPlay-win64
          path: |
            build/ImPlay-*.msi
            build/ImPlay-*.zip
  publish:
    needs: [linux, macos, win]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: continuous
          force_push_tag: true
      - uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: continuous
          artifacts: "ImPlay-linux/*,ImPlay-macOS/*,ImPlay-win64/*"
          allowUpdates: true
          prerelease: true
          name: Continuous build
          body: |
            # Install
            ## Windows
            - MSI
              - Download `ImPlay-win64.msi`
              - Run the MSI
              - Run ImPlay from Start Menu
            - Zip
              - Download `ImPlay-win64.zip`
              - Extract the zip
              - Run `ImPlay.exe`
            ## macOS
            - Download `ImPlay-macOS.dmg`
            - Double click the dmg to show it's contents
            - Drag the application to Applications
            - Run ImPlay from Launchpad
            ## Linux
            - Debian Package
              - Download `ImPlay-linux64.deb`
              - Install: `sudo apt install ./ImPlay-linux64.deb`
              - Run `ImPlay`
            - AppImage
              - Download `ImPlay-linux64.AppImage`
              - Run `chmod u+x ImPlay-linux64.AppImage && ./ImPlay-linux64.AppImage`

